name: deploy
on: 
  push:
    branches:
      - master
    tags:
      - v*  
  pull_request:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-20.04
    name: Deploy Flutter Web to remote server 
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter 3.3.5
        uses: subosito/flutter-action@v1    
        with:
          flutter-version: '3.3.5'
      - run: flutter clean    
      - run: flutter pub get
      - name: Build flutter web
        run: flutter build web
      - name: Delete web folder in Remote server
        uses: appleboy/ssh-action@master
        with:
          script: |
            rm -r admpanel/web
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}  
      - name: Deploy the package to the remote server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: build/web
          remote: admpanel/web # My remote directory
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
      - name: Run a script on remote server (start the application)
        if: always()
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd admpanel/
            kill -9 `cat pid.txt` && rm pid.txt
            cd web/
            nohup python3 -m http.server 8000 > /root/admpanel/web.log 2>&1 & echo $! > /root/admpanel/pid.txt
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
